setup:
 count: 1
 vesprotocol: http  # use `https` for the real VES
 vesip: 172.17.0.1  # use 172.17.0.1 to communicate with localhost
 vesport: 10000
 vesresource: eventListener
 vesversion: v7
 ipstart: 10.11.0.16
 user: ""
 password: ""
 ipfileserver: 127.0.0.1
 typefileserver: sftp
data:
 commonEventHeaderParams:
  sourceName: pyint-000
  reportingEntityName: pyint-000
